# Generated by Django 2.0.5 on 2018-06-23 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180622_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_ptr',
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='groups.Group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
