# Generated by Django 2.1 on 2018-08-10 18:51

import core.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_use_amount_field'),
        ('users', '0006_report_approve_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance_amount',
            field=core.db.models.fields.AmountField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='reporting_currency',
            field=models.ForeignKey(default=322, on_delete=django.db.models.deletion.PROTECT, to='currencies.Currency'),
            preserve_default=False,
        ),
    ]
