# Generated by Django 2.1 on 2018-08-10 17:51

import core.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_auto_20180707_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sum',
            name='amount',
            field=core.db.models.fields.AmountField(decimal_places=2, max_digits=15),
        ),
    ]
