# Generated by Django 2.0.5 on 2018-06-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180616_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
