# Generated by Django 2.0.5 on 2018-07-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'REJECTED')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
